Added JSONBuddy Cli tool
json-schema-org/json-schema-org.github.io pull request #455
Opened 2022-06-29 08:19 UTC by Clemens-U

2022-06-29 10:29 UTC, Relequestual requested changes
I suspect people will want to know if you're using a standard open source license or not. The suggestion should mak that clearer.
Thanks for adding! =]

2022-06-29 10:29 UTC, Relequestual commented on _data/validator-libraries-modern.yml
> +      license: Free and commercial versions
```suggestion
      license: Free and commercial versions (proprietary)
```

2022-07-01 08:21 UTC, Clemens-U commented
Is there anything open from my side because of the requested change?

2022-07-29 14:27 UTC, Relequestual approved these changes

2022-07-29 14:28 UTC, Relequestual commented
Sorry for the delay. Thanks again for your work!

2022-08-22 01:36 UTC, handrews commented
Not sure why this wasn't merged.  @gregsdennis you might need to update your most recent PR, but I don't want to ask this person to change theirs a month after approval.

2022-08-22 01:36 UTC, merged